# Generated by Django 6.0.5 on 2026-06-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadjokes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
